### ISSUE TITLE
Add Vuetify

### ISSUE THREAD

**Issue by tctcodes** [USM-ACM-IEEE/acmWebsite#12]
# ACM Website

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/USM-ACM/acmWebsite/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in an [already closed issue](https://github.com/USM-ACM/acmWebsite/issues?q=is%3Aissue+is%3Aclosed)**.

## Issue Type

- [ ] [Bug](https://github.com/USM-ACM/acmWebsite/blob/master/CONTRIBUTING.md#bug-reports)
- [x] [Feature](https://github.com/USM-ACM/acmWebsite/blob/master/CONTRIBUTING.md#feature-requests)

## Description
Add Vuetify to the website
(Add images if possible)

## Steps to reproduce (if applicable)

(Add link to a demo on https://jsfiddle.net or similar if possible)

**Comment by BCRevels** [comment]
Vuetify PR Merged, Closing Issue
